// --- Cores ---
#define PRETO CRGB(0,0,0)
#define VERDE CRGB(20,255,29)
#define BRANCO CRGB(255,255,255)
#define AMARELO CRGB(255,242,0)
#define VERMELHO CRGB(237,28,36)
#define AZUL CRGB(77,109,243)
#define ROSA CRGB(255,163,177)
#define ARVORE CRGB(34,177,76)
#define RED CRGB(255,0,0)

int xy(int x, int y) {
  if (x % 2 == 0) return x * HEIGHT + y;
  else return x * HEIGHT + (HEIGHT - 1 - y);
}


// --- SUA IMAGEM ORIGINAL (organizada apenas) ---
const CRGB image16x16[256] = {
  PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,
  PRETO,PRETO,PRETO,VERDE,BRANCO,PRETO,VERMELHO,PRETO,PRETO,BRANCO,PRETO,BRANCO,PRETO,BRANCO,PRETO,PRETO,
  PRETO,VERDE,PRETO,VERDE,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,BRANCO,PRETO,BRANCO,PRETO,PRETO,PRETO,
  PRETO,VERDE,PRETO,VERDE,VERDE,PRETO,PRETO,PRETO,PRETO,BRANCO,PRETO,BRANCO,PRETO,BRANCO,PRETO,PRETO,
  PRETO,VERDE,VERDE,PRETO,VERDE,PRETO,PRETO,PRETO,PRETO,PRETO,BRANCO,PRETO,BRANCO,PRETO,PRETO,PRETO,
  PRETO,PRETO,VERDE,VERDE,VERDE,PRETO,PRETO,PRETO,PRETO,BRANCO,PRETO,BRANCO,PRETO,BRANCO,PRETO,PRETO,
  PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,
  PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,
  PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,
  PRETO,AMARELO,AMARELO,AMARELO,ARVORE,PRETO,PRETO,PRETO,PRETO,BRANCO,PRETO,PRETO,BRANCO,PRETO,PRETO,PRETO,
  PRETO,VERMELHO,VERMELHO,AMARELO,ARVORE,PRETO,PRETO,PRETO,BRANCO,BRANCO,BRANCO,BRANCO,BRANCO,BRANCO,PRETO,PRETO,
  PRETO,AZUL,VERMELHO,VERMELHO,ARVORE,PRETO,PRETO,PRETO,PRETO,BRANCO,PRETO,PRETO,BRANCO,PRETO,PRETO,PRETO,
  PRETO,AZUL,AZUL,VERDE,ARVORE,PRETO,PRETO,PRETO,PRETO,BRANCO,PRETO,PRETO,BRANCO,PRETO,PRETO,PRETO,
  PRETO,AZUL,VERDE,VERDE,VERDE,PRETO,PRETO,PRETO,BRANCO,BRANCO,BRANCO,BRANCO,BRANCO,BRANCO,PRETO,PRETO,
  PRETO,ROSA,ROSA,ROSA,ROSA,PRETO,PRETO,PRETO,PRETO,BRANCO,PRETO,PRETO,BRANCO,PRETO,PRETO,PRETO,
  PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO,PRETO
};

void mostrarImagem(){
  for(int y=0; y<HEIGHT; y++){
    for(int x=0; x<WIDTH; x++){
      leds[xy(x,y)] = image16x16[y*WIDTH + x];
    }
  }
  FastLED.show();
}