
// --- Definição de Cores Padrão ---
#define PRETO   CRGB(0,0,0)
#define BRANCO  CRGB(255,255,255)

// --- Cores Personalizadas ---
#define ROSA_ROXO       CRGB(212,0,255)
#define VERDE_LIMAO     CRGB(167,255,0)
#define MARROM_ESCURO   CRGB(52,25,25)
#define VERMELHO        CRGB(255,0,0)
#define AZUL_PETROLEO   CRGB(0,1,93)
#define VERDE_MUSGO     CRGB(141,205,20)
#define CIANO_CLARO     CRGB(0,255,227)
#define AZUL      CRGB(0,100,255)
#define AZUL_FORTE      CRGB(0,36,255)
#define AMARELO_CLARO CRGB(255,255,20)
#define AZUL_ESCURO   CRGB(0,50,200)

// -------------------- IMAGEM INICIAL --------------------

// --- Matriz 16x16 ---
CRGB velhaboard[16*16] = {
  PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO,

  PRETO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, PRETO,
  PRETO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, PRETO,
  PRETO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, PRETO,
  PRETO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, PRETO,

  PRETO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, PRETO,
 
  PRETO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, PRETO,
  PRETO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, PRETO,
  PRETO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, PRETO,
  PRETO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, PRETO,

  PRETO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, AMARELO_CLARO, PRETO,
  
  PRETO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, PRETO,
  PRETO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, PRETO,
  PRETO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, PRETO,
  PRETO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, AMARELO_CLARO, PRETO, PRETO, PRETO, PRETO, PRETO,

  PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO, PRETO,
};

const CRGB criaX[4*4] = {
  VERMELHO, PRETO, PRETO, VERMELHO,
  PRETO, VERMELHO, VERMELHO, PRETO,
  PRETO, VERMELHO, VERMELHO, PRETO,
  VERMELHO, PRETO, PRETO, VERMELHO,
};
const CRGB criaO[4*4] = {
  AZUL, AZUL, AZUL, AZUL,
  AZUL, PRETO, PRETO, AZUL,
  AZUL, PRETO, PRETO, AZUL,
  AZUL, AZUL, AZUL, AZUL,
};

